### PR TITLE
BEP 0044 implementation.

### LINKED ISSUE #26: Bep044 - dht storage - it's not a issue.
Is there Simeone working on this?
I'm planning an app that uses Sgt storage and your packet seems to be really interesting.

### PR DESCRIPTION
**Pull request by ajnavarro**
BEP 0044 implementation: Storing arbitrary data in the DHT.

- Added two new methods to Server struct; Put and Get.
- Item storage is pluggable, an in-memory implementation is provided by default.
- Added some integration and unit tests to check that everything is working properly.

It is my first PR to this repository, do not hesitate to provide all the needed feedback.

Closes #26 

Signed-off-by: Antonio Navarro Perez <antnavper@gmail.com>

### CODE REVIEW

**Comment by anacrolix** [comment]
Sorry it's not documented clearly, but did you see https://pkg.go.dev/github.com/anacrolix/dht/v2@v2.10.5/exts/getput?

**Comment by anacrolix** [comment]
It looks like you've essentially included the mutable parts of BEP44 nicely, it fits over what was already there quite nicely.

**Comment by anacrolix** [comment]
Oh and see my comment about where to put the store.

**Comment by ajnavarro** [comment]
> Happy to merge what you have so far. Just curious about using []byte instead of interface{} for `v` in places, what's the idea there?

Yep, you are right, that change is not needed. I rolled it back. Much clearer now.

> Let's put this module in exts/getput or something? It's specific to BEP 44. Happy to rename the exts/getput to ./bep44 or something in advance.

I changed store to `bep44`, but I cannot move `ext/getput` files to `bep44` for cyclic dependencies error.

**Comment by anacrolix** [comment]
Thanks for doing that. I imagine you have some code built on top of this, and if it's okay I'll probably rearrange things a bit after merging this.

**Pull request merged**
