### PR TITLE
Patch unaligned 64-bit atomic operation panic

### PR DESCRIPTION
**Pull request by silentmurdock**
Fix unaligned 64-bit atomic operation panic to support 32-bit architectures too.

### CODE REVIEW

**Comment by anacrolix** [comment]
Damn, does it really take that much?!

**Comment by anacrolix** [comment]
Was moving the stat block to the beginning of the struct not enough? What if it's detached and pointed to instead of embedded?

**Comment by silentmurdock** [comment]
You're right, I looked through the code a little more and found that if i move the "traversal" block to the beginning of "Announce" struct in "announce.go" that also solves the problem. Working on 32-bit systems.

I am revoking this pull request.
Please modify the code.

**Comment by silentmurdock** [comment]
A simpler solution is also available.

**Comment by anacrolix** [comment]
@silentmurdock I commented about this in https://github.com/anacrolix/torrent/issues/483#issuecomment-835695175 but got feedback to the contrary from https://github.com/compliment. Can you confirm the patch in the linked comment fix this for you on the platforms you're using?

**Comment by compliment** [comment]
> You're right, I looked through the code a little more and found that if i move the "traversal" block to the beginning of "Announce" struct in "announce.go" that also solves the problem. Working on 32-bit systems.
> 
This is https://github.com/anacrolix/dht/commit/fd60ad06b4827d42a76235103e88b20e633db27c
I tried it with with https://github.com/anacrolix/torrent/tree/master/cmd/torrent for linux 386 and got 

```
panic: unaligned 64-bit atomic operation

goroutine 795 [running]:
runtime/internal/atomic.panicUnaligned()
	runtime/internal/atomic/unaligned.go:8 +0x2d
runtime/internal/atomic.Xadd64(0x9e321e4, 0x1, 0x0, 0x0, 0x0)
	runtime/internal/atomic/asm_386.s:107 +0x11
github.com/anacrolix/dht/v2.(*traversal).wrapQuery(0x9e321e4, 0x86c4250, 0x9c753c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/anacrolix/dht/v2@v2.9.2-0.20210509011734-fd60ad06b482/traversal.go:115 +0x52
github.com/anacrolix/dht/v2.(*traversal).run.func1.1(0x9c0e008)
	github.com/anacrolix/dht/v2@v2.9.2-0.20210509011734-fd60ad06b482/traversal.go:156 +0x35
github.com/anacrolix/dht/v2.(*traversal).beginQuery.func1.1(0x0)
	github.com/anacrolix/dht/v2@v2.9.2-0.20210509011734-fd60ad06b482/traversal.go:179 +0x93
github.com/anacrolix/dht/v2.(*Server).beginQuery.func1.1()
	github.com/anacrolix/dht/v2@v2.9.2-0.20210509011734-fd60ad06b482/server.go:745 +0x23
created by github.com/anacrolix/dht/v2.(*traversal).run
	github.com/anacrolix/dht/v2@v2.9.2-0.20210509011734-fd60ad06b482/traversal.go:164 +0x83 
```
Are you this worked for you and you didn't have your own patch applied?

**Comment by anacrolix** [comment]
Thanks for chasing this up. I'll follow this up when you guys determine the best way forward.

**Comment by silentmurdock** [comment]
This is [fd60ad0](https://github.com/anacrolix/dht/commit/fd60ad06b4827d42a76235103e88b20e633db27c)

> Are you sure this worked for you and you didn't have your own patch applied?

It didn’t work for me either, I used my own patch solution. (torrent-issue-483_solution_2.zip)

Anacrolix's solution is not working, because he modified only the "traversal.go" file, but "announce.go" has an other struct that need to modified. I extended anacrolix's solution (torrent-issue-483_solution_1.zip)

Both versions work, but I think the second solution is simpler.
Please write over the specified files and test it.
[torrent-issue-483_solution_1.zip](https://github.com/anacrolix/dht/files/6539258/torrent-issue-483_solution_1.zip)
[torrent-issue-483_solution_2.zip](https://github.com/anacrolix/dht/files/6539259/torrent-issue-483_solution_2.zip)

Which one do we use?

**Comment by anacrolix** [comment]
I think mine is simpler. It would be great if this was checked in CI. It's recently moved to GitHub actions if you're keen/know how to implement that.

**Comment by silentmurdock** [comment]
Unfortunately, CircleCI does not contain 32-bit images. I don’t feel so confident in using CI. Maybe if we compile the 32-bit code on a 64-bit system image and run the tests there. (run: GOOS = linux GOARCH = arm GOARM = 6)

**Comment by silentmurdock** [comment]
@anacrolix Can you add the changes because my app doesn't work without it? I don’t want to use a vendor library in my project. I tested it manually on arm, linux, windows 32 bit systems. I will be working on a CI test solution in the future.
Or do I restore the branch, modify, and create a new pull requests?

**Pull request closed without merging**
