### PR TITLE
Add transmission and vuze bootstrap nodes

### PR DESCRIPTION
**Pull request by dz0ny**
This adds boostrap nodes of other two popular clients

### CODE REVIEW

**Comment by anacrolix** [comment]
Seems legit, but those nodes don't seem to be active?

**Comment by anacrolix** [comment]
anacrolix@anacrolix-MBP:~/gopath/src/github.com/anacrolix/dht$ godo -v -race ./cmd/dht-ping router.utorrent.com:6881 router.bittorrent.com:6881 dht.transmissionbt.com:6881 dht.aelitis.com:6881
2017/09/06 15:31:35 main.go:28: dht server on [::]:65230 with id 52fdfc072182654f163f5f0f9a621d729566c74d
router.utorrent.com:6881: ebff36697351ff4aec29cdbaabf2fbe3467cc267 ✔: 945.968659ms
router.bittorrent.com:6881: 32f54e697351ff4aec29cdbaabf2fbe3467cc267 ✔: 801.921412ms
dht.transmissionbt.com:6881: 14.882604849s: query timed out
dht.aelitis.com:6881: 15.084774462s: query timed out

**Comment by dz0ny** [comment]
Maybe they are blocked from your provider? I still see that they are in code base https://github.com/transmission/transmission/blob/0378ee829872c51ae18b77cd19cb2ad6e17d116b/libtransmission/tr-dht.c#L302.

I'll try ping from home location.

**Comment by anacrolix** [comment]
I've tried from a few locations. They both resolve, but aren't responding.

**Pull request merged**
